# Generated by Django 5.1.1 on 2024-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(default=1, upload_to='Image/'),
            preserve_default=False,
        ),
    ]
